name: 'Run unit-tests'

on:
  push:

  pull_request:

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  build-image:
    name: Build and push image 
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build and push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker build -t $GITHUB_REGISTRY/starodubcevdv/c2py:latest -t $GITHUB_REGISTRY/starodubcevdv/c2py:${{ github.sha }} .
          docker push $GITHUB_REGISTRY/starodubcevdv/c2py:latest
          docker push $GITHUB_REGISTRY/starodubcevdv/c2py:${{ github.sha }}